name: Manual Vulnerability Check Trigger

on:
  workflow_dispatch:

env:
  TERM: dumb
jobs:
  call-vuln-check:
    uses: ./.github/workflows/vuln-check.yaml
    with:
      target-ref: ${{ github.ref_name }}
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
